run:
  go: "1.24"
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    enable-all: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
